language: python
python:
- '3.6'
notifications:
  email: false
install:
# wxPython is not on PyPI for Linux
- sed -i 's/"wxpython/#"wxpython/g' setup.py
- travis_retry pip install -e .
# coverage packages
- travis_retry pip install codecov coverage
- pip freeze
script:
- coverage run --source=pyscanfcs setup.py test
- coverage report -m
- codecov

