language: python
python:
- '2.7'
notifications:
  email: false
install:
# everything else
- travis_retry pip install .
# coverage packages
- travis_retry pip install codecov coverage
- pip freeze
script:
- coverage run --source=pyscanfcs setup.py test
- coverage report -m
- codecov

