language: python
python:
- '3.6'
notifications:
  email: false
install:
# wxPython is not on PyPI for Linux
- travis_retry pip install astropy matplotlib multipletau numpy scikit-image scipy cython
- travis_retry pip install . --no-deps
# coverage packages
- travis_retry pip install codecov coverage
- pip freeze
script:
- coverage run --source=pyscanfcs setup.py test
- coverage report -m
- codecov

