clone_depth: 256
build: off
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
environment:
  matrix:
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  # Install InnoSetup and add to path
  # Copied from
  # https://github.com/Phonations/Joker/blob/master/appveyor.yml
  - appveyor-retry choco install -y InnoSetup

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # CONDA installs
  # Pinned versions are defined in .appveyor\pinned
  - xcopy .appveyor\pinned %PYTHON%\conda-meta\ /Y
  - "appveyor-retry conda install --yes --quiet matplotlib numpy pip scipy wxpython"
  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "pip install cython wheel"
  - "pip install pyinstaller==3.5"
  - "pip install -e ."
  # Show the installed packages
  - "pip freeze"

test_script:
  - "pip install coverage"
  - "pip install codecov"
  - "coverage run --source=pyscanfcs ./setup.py test"
  - "coverage report -m"
  - "codecov || exit 0"

after_test:
  # If tests are successful, create a whl package for the project.
  - "python setup.py bdist_wheel"
  - ps: "ls dist"
  # Run pyinstaller
  # This will create the "win7_innosetup.iss" file
  - "pyinstaller -y --log-level=WARN .appveyor\\PyScanFCS_win7.spec"
  # Create InnoSetup installers
  # Set InnoSetup path here, because Cython complained about it.
  - set PATH=%PATH%;"C:\\Program Files (x86)\\Inno Setup 5"
  - iscc /Q win7_innosetup.iss

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*
  # InnoSetup files
  - path: Output\*

deploy:
  provider: GitHub
  auth_token:
    secure: TODO_not_set_yet
  artifact: /.*\.exe/, /.*\.whl/
  draft: true
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
